# For mantles
- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 100000 #20 hrs

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
  groupBy: "jumpskirt"

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
  groupBy: "jumpskirt"

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
  groupBy: "jumpskirt"

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatFoxyHead

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatFoxyHead

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterSuitFoxy

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterSuitFoxy
