- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    pocket1: BaseUplinkRadioT
    jumpsuit: ClothingUniformJumpsuitMojahed
    belt: ClothingBeltSecurityWebbing
    head: ClothingHeadHatKufiaHat
    shoes: ClothingShoesBootsCombatFilled