- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hop
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: LibrarianGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    id: LibrarianPDA
    ears: ClothingHeadsetSecurity
    pocket1: BaseUplinkRadioCT # for making named bestsellers
    head: ClothingHeadHelmetBasic
    belt: ClothingBeltMilitaryWebbing

- type: chameleonOutfit
  id: LibrarianChameleonOutfit
  job: Librarian
  equipment:
    head: ClothingHeadHatCanadaBeanie
    eyes: ClothingEyesGlassesJamjar
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedGreen
    outerClothing: ClothingOuterWinterColorGreen
    gloves: ClothingHandsGlovesColorBlack
