- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: JobMime
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 0 #4 hrs
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hop
  accessGroups:
  - AllAccess
  access:
  - CentralCommand


- type: startingGear
  id: MimeGear
  equipment:
    shoes: ClothingShoesBootsCombatFilled
    id: MimePDA
    pocket1: BaseUplinkRadioT
    ears: ClothingHeadsetService
    head: ClothingHeadHatUshanka

- type: chameleonOutfit
  id: MimeChameleonOutfit
  job: Mime
  equipment:
    head: ClothingHeadHatMimesoft
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingNeckScarfStripedZebra
    outerClothing: ClothingOuterWinterMime
