- type: job
  id: Musician
  name: job-name-musician
  description: job-description-musician
  playTimeTracker: JobMusician
  startingGear: MusicianGear
  icon: "JobIconMusician"
  supervisors: job-supervisors-hire
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: MusicianGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    id: MusicianPDA
    ears: ClothingHeadsetService
    pocket1: BaseUplinkRadioCT
    shoes: ClothingShoesBootsCombatFilled
    belt: ClothingBeltMilitaryWebbing
    head: ClothingHeadHatDustHat
